//
//  TestConversatios.swift
//  Trial Manager
//
//  Created by Milind Contractor on 23/1/26.
//

/// IMPORTANT
/// This file was generated by AI
/// It exists only for testing the user interfaces.

import Foundation

// MARK: - Sample Conversation Data for Testing

extension Array where Element == ConversationItem {
    static var sampleConversations: [[ConversationItem]] {
        [
            // Conversation 1: Initial Check-in
            Self.conversation1_initialCheckin,
            
            // Conversation 2: Subscription Analysis
            Self.conversation2_subscriptionAnalysis,
            
            // Conversation 3: Overspending Alert
            Self.conversation3_overspendingAlert,
            
            // Conversation 4: Budget Help
            Self.conversation4_budgetHelp,
            
            // Conversation 5: Savings Goal
            Self.conversation5_savingsGoal
        ]
    }
    
    // MARK: Conversation 1: Initial Financial Check-in
    static var conversation1_initialCheckin: [ConversationItem] {
        [
            ConversationItem(
                personResponding: .person,
                text: "Hey, can you give me an overview of my finances?"
            ),
            ConversationItem(
                personResponding: .ai,
                text: """
                Hi! Let me break down your current financial situation:
                
                💰 Current Balance: $2,450.00
                📅 Next Paycheck: January 30 ($3,200)
                
                Recent Spending (Last 7 days):
                • Food: $245 (5 transactions)
                • Entertainment: $89 (Netflix, movie tickets)
                • Shopping: $156 (Amazon, Target)
                
                You're tracking well this month! You've spent $1,680 out of your $3,200 income, leaving you with a healthy cushion before your next paycheck.
                
                One thing I noticed: You're spending about $35/day on food. Would you like some tips on reducing dining costs?
                """
            ),
            ConversationItem(
                personResponding: .person,
                text: "Yeah, that sounds high. What do you suggest?"
            ),
            ConversationItem(
                personResponding: .ai,
                text: """
                Great awareness! Here's a realistic plan based on your habits:
                
                Current: ~$35/day ($1,050/month)
                Goal: ~$25/day ($750/month)
                Savings: $300/month 💵
                
                How to get there:
                1. Meal prep 3 dinners/week (saves ~$60/week)
                2. Make coffee at home 4 days/week (saves ~$20/week)
                3. Keep your weekend dining out - you enjoy it!
                
                This isn't about eliminating fun, just being smarter about weekday spending. Want me to track your progress?
                """
            ),
            ConversationItem(
                personResponding: .person,
                text: "Sure, let's try it!"
            ),
            ConversationItem(
                personResponding: .ai,
                text: """
                Awesome! I'll check in with you next week to see how it's going. 
                
                Quick tip: When you're tempted to order takeout, ask yourself "Is this a treat or just convenient?" If it's just convenience, that's your savings opportunity! 
                
                You've got this! 💪
                """
            )
        ]
    }
    
    // MARK: Conversation 2: Subscription Analysis
    static var conversation2_subscriptionAnalysis: [ConversationItem] {
        [
            ConversationItem(
                personResponding: .person,
                text: "I feel like I'm paying for too many subscriptions. Can you help?"
            ),
            ConversationItem(
                personResponding: .ai,
                text: """
                Let's audit your subscriptions! Here's what you're currently paying:
                
                Monthly Subscriptions:
                • Netflix: $15.49
                • Spotify: $10.99
                • Disney+: $13.99
                • Apple One: $19.95
                • Adobe Creative Cloud: $54.99
                • Planet Fitness: $24.99
                
                📊 Total: $140.40/month ($1,684.80/year)
                
                I see some optimization opportunities:
                
                1. You have Apple One AND Spotify - you're paying for Apple Music twice! Cancel Spotify → Save $131.88/year
                
                2. Disney+ renews in 3 days, but you haven't watched anything in 2 months. Cancel? → Save $167.88/year
                
                3. Adobe CC is your biggest expense. Do you use all the apps? The Photography plan is $19.99 if you only need Photoshop/Lightroom → Save $420/year
                
                Potential total savings: $719.76/year! 
                
                Which ones would you like to reconsider?
                """
            ),
            ConversationItem(
                personResponding: .person,
                text: "Oh wow, I didn't realize I had both Spotify and Apple Music! Cancel Spotify. And yeah, I barely use Disney+."
            ),
            ConversationItem(
                personResponding: .ai,
                text: """
                Smart moves! Here's your new subscription breakdown:
                
                ✅ Cancelled:
                • Spotify ($10.99/mo)
                • Disney+ ($13.99/mo)
                
                💰 New Monthly Total: $115.42
                📉 Savings: $24.98/month ($299.76/year)
                
                That's almost $300 back in your pocket! And you still have Netflix, Apple Music, and your gym membership.
                
                Pro tip: Set a calendar reminder for 6 months from now to review your subscriptions again. They have a way of sneaking back up on us! 😄
                
                Want me to remind you?
                """
            ),
            ConversationItem(
                personResponding: .person,
                text: "Yes please!"
            )
        ]
    }
    
    // MARK: Conversation 3: Overspending Alert
    static var conversation3_overspendingAlert: [ConversationItem] {
        [
            ConversationItem(
                personResponding: .person,
                text: "How am I doing this month?"
            ),
            ConversationItem(
                personResponding: .ai,
                text: """
                I need to give you a heads up about your spending:
                
                ⚠️ You're 18 days into the month and you've already spent $2,890 out of your $3,200 income.
                
                That leaves you with only $310 for the next 12 days until your next paycheck.
                
                Here's where it went:
                • Shopping: $1,240 (43% of income!) 🚨
                • Food: $680
                • Entertainment: $420
                • Utilities: $350
                • Other: $200
                
                The shopping category is the concern. I see:
                • Amazon: $340
                • Best Buy: $450 (new headphones?)
                • Nike: $280
                • Target: $170
                
                At this rate, you might dip into savings or overdraft before payday. Can we talk about what triggered these purchases?
                """
            ),
            ConversationItem(
                personResponding: .person,
                text: "Yeah, I bought new headphones and some clothes. Probably should have waited."
            ),
            ConversationItem(
                personResponding: .ai,
                text: """
                I get it - sometimes we need things! But let's make a plan so you don't stress the next 12 days:
                
                Survival Budget (until Jan 30):
                • Food: $150 ($12.50/day - groceries only, no takeout)
                • Gas/Transport: $80
                • Emergency buffer: $80
                
                Challenge: Can you make it to payday without spending more? 
                
                Tips:
                1. Grocery shop once this week with a strict list
                2. No "browsing" on Amazon or stores
                3. Unsubscribe from promotional emails temporarily
                
                Next month, let's set up a "fun money" budget of $200-300 for shopping so you don't feel deprived but also don't overshoot. Sound good?
                """
            ),
            ConversationItem(
                personResponding: .person,
                text: "That makes sense. I can do that."
            ),
            ConversationItem(
                personResponding: .ai,
                text: """
                You've got this! 💪
                
                Remember: It's not about never spending on things you enjoy. It's about being intentional and planning for it.
                
                I'll check in with you in a few days to see how you're doing. And on Feb 1st, we'll set up that fun money budget together!
                """
            )
        ]
    }
    
    // MARK: Conversation 4: Budget Planning Help
    static var conversation4_budgetHelp: [ConversationItem] {
        [
            ConversationItem(
                personResponding: .person,
                text: "I want to create a budget but don't know where to start"
            ),
            ConversationItem(
                personResponding: .ai,
                text: """
                Perfect! Let me create a personalized budget based on your actual spending over the last 3 months.
                
                Your Income: $3,200/month
                
                Based on the 50/30/20 rule:
                • Needs (50%): $1,600
                • Wants (30%): $960
                • Savings (20%): $640
                
                Here's what I recommend FOR YOU:
                
                💡 NEEDS ($1,650):
                • Rent: $1,100
                • Utilities: $150
                • Groceries: $300
                • Insurance: $100
                
                🎉 WANTS ($850):
                • Dining Out: $250
                • Entertainment: $150
                • Shopping: $300
                • Subscriptions: $115
                • Coffee/treats: $35
                
                💰 SAVINGS ($700):
                • Emergency Fund: $500
                • Fun Savings: $200
                
                This is based on YOUR habits, not some generic template. Notice I gave you room for shopping and dining out because I know you enjoy those!
                
                Does this feel realistic to you?
                """
            ),
            ConversationItem(
                personResponding: .person,
                text: "Yeah, but I don't think I can save $700 right now"
            ),
            ConversationItem(
                personResponding: .ai,
                text: """
                Totally fair! Let's adjust. What feels doable?
                
                How about we start with:
                • Savings: $400/month
                
                That gives you an extra $300 for flexibility:
                
                Updated Budget:
                • Needs: $1,650
                • Wants: $1,150 (more breathing room!)
                • Savings: $400
                
                Even $400/month is $4,800/year - that's a solid emergency fund in 12 months!
                
                We can always increase savings later once this becomes comfortable. Building the habit is more important than the amount.
                
                Want to try this for a month and see how it feels?
                """
            ),
            ConversationItem(
                personResponding: .person,
                text: "Yes, that sounds much better!"
            )
        ]
    }
    
    // MARK: Conversation 5: Savings Goal Progress
    static var conversation5_savingsGoal: [ConversationItem] {
        [
            ConversationItem(
                personResponding: .person,
                text: "How much have I saved this month?"
            ),
            ConversationItem(
                personResponding: .ai,
                text: """
                Great question! Let me calculate:
                
                📊 January Savings Report:
                
                Starting Balance (Jan 1): $2,100
                Current Balance: $2,890
                Net Savings: +$790 🎉
                
                Income received: $3,200
                Total spent: $2,510
                
                Breakdown:
                ✅ Came in under budget on:
                • Food: $420 (budgeted $500) - saved $80!
                • Entertainment: $95 (budgeted $150) - saved $55!
                
                ⚠️ Went over on:
                • Shopping: $380 (budgeted $300) +$80
                
                Overall: You saved 24.7% of your income this month! That's ABOVE your 20% goal. Amazing work! 🌟
                
                At this rate, you'll have:
                • 3 months: $2,370 saved
                • 6 months: $4,740 saved
                • 1 year: $9,480 saved
                
                You're building real financial security. Keep it up!
                """
            ),
            ConversationItem(
                personResponding: .person,
                text: "Wow! I didn't realize I was doing that well!"
            ),
            ConversationItem(
                personResponding: .ai,
                text: """
                You should be proud! You're making smart choices and it's paying off.
                
                Here's what's working:
                1. You're meal prepping more (I see fewer takeout charges)
                2. You cancelled those unused subscriptions
                3. You're thinking before impulse buying
                
                Small consistent wins = big results over time.
                
                Since you're ahead of your goal, want to set a new challenge? Maybe save for something specific - a trip, emergency fund, new tech?
                """
            ),
            ConversationItem(
                personResponding: .person,
                text: "I'd love to save for a vacation to Japan next year"
            ),
            ConversationItem(
                personResponding: .ai,
                text: """
                Japan! Great choice! Let's make it happen:
                
                Typical Japan trip cost: $3,500-5,000
                Let's target: $4,000
                
                Timeline: 12 months
                Monthly savings needed: $334
                
                The good news? You're already saving ~$790/month!
                
                Here's the plan:
                • Keep your current savings rate
                • Dedicate $334/month to "Japan Fund"
                • Remaining $456/month to emergency fund
                
                In 12 months:
                ✈️ Japan Fund: $4,008
                🏦 Emergency Fund: $5,472
                
                You'll take your dream trip AND have a solid safety net!
                
                Want me to track this goal for you?
                """
            )
        ]
    }
}
